name: android_crash_on_exit
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  chewie: 0.9.10
  video_player: 0.10.8+1
  webview_flutter: 0.3.19+9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/SampleVideo_1280x720_5mb.mp4